# All-in-one script for the workflow automation bot using Streamlit.
import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF
import smtplib
import logging
import os
from dotenv import load_dotenv
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import streamlit as st
from io import BytesIO

# --- 0. Load Environment Variables ---
# Create a .env file or set Streamlit secrets with your credentials:
# SMTP_SERVER="smtp.example.com"
# SMTP_PORT="587"
# SMTP_USER="your_email@example.com"
# SMTP_PASSWORD="your_password"
# MAIL_TO="recipient@example.com"
load_dotenv()

# --- 1. Configuration ---
OUTPUT_DIR = 'output'
LOG_FILE = 'workflow.log'
FONT_PATH = 'NanumGothic.ttf' # Download and place a .ttf font file in the directory

# --- 2. Setup Logging & Output Dir ---
logging.basicConfig(filename=LOG_FILE, level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# --- 3. Function Definitions (Modules) ---
# These functions are modified to accept a logger function for Streamlit feedback.

def st_logger(message, level='info'):
    """Logs messages to both the Streamlit UI and the log file."""
    log_map_st = {'info': st.info, 'warning': st.warning, 'error': st.error}
    log_map_file = {'info': logging.info, 'warning': logging.warning, 'error': logging.error}
    
    log_map_st.get(level, st.info)(message)
    log_map_file.get(level, logging.info)(message)


def validate_data(df, logger):
    logger('Starting data validation...')
    if df.isnull().values.any():
        logger('Null values found in data. Dropping rows with nulls.', level='warning')
        df = df.dropna()
    logger('Data validation complete.')
    return df

def summarize_data(df, logger):
    logger('Summarizing data...')
    summary = df.describe().to_string()
    logger('Data summary created.')
    return summary

def create_visualization(df, column_to_plot, logger):
    logger(f'Creating visualization for column: {column_to_plot}...')
    if column_to_plot not in df.columns:
        msg = f"Column '{column_to_plot}' not found in the data."
        logger(msg, level='error')
        raise ValueError(msg)
    
    if not pd.api.types.is_numeric_dtype(df[column_to_plot]):
        msg = f"Column '{column_to_plot}' is not numeric. Cannot create histogram."
        logger(msg, level='warning')
        raise TypeError(msg)

    plt.figure()
    df[column_to_plot].hist()
    plt.title(f'Histogram of {column_to_plot}')
    plt.xlabel(column_to_plot)
    plt.ylabel('Frequency')
    chart_path = os.path.join(OUTPUT_DIR, 'summary_chart.png')
    plt.savefig(chart_path)
    plt.close()
    logger(f'Chart saved to {chart_path}')
    return chart_path

def generate_pdf_report(summary, chart_path, logger):
    logger('Generating PDF report...')
    pdf_path = os.path.join(OUTPUT_DIR, 'report.pdf')

    if not os.path.exists(FONT_PATH):
        msg = f"Font file not found at {FONT_PATH}. Cannot generate PDF."
        logger(msg, level='error')
        raise FileNotFoundError(msg)

    pdf = FPDF()
    pdf.add_font('NanumGothic', '', FONT_PATH, uni=True)
    pdf.add_page()
    
    pdf.set_font("NanumGothic", size=16)
    pdf.cell(200, 10, txt="Workflow Automation Report", ln=True, align='C')
    
    pdf.set_font("NanumGothic", size=12)
    pdf.cell(200, 10, txt="Data Summary", ln=True, align='L')
    pdf.set_font("NanumGothic", size=10)
    pdf.multi_cell(0, 5, txt=summary)
    
    if chart_path and os.path.exists(chart_path):
        pdf.add_page()
        pdf.set_font("NanumGothic", size=12)
        pdf.cell(200, 10, txt="Data Visualization", ln=True, align='L')
        pdf.image(chart_path, w=180)

    pdf.output(pdf_path)
    logger(f'PDF report saved to {pdf_path}')
    return pdf_path

def send_email_with_attachment(report_path, email_settings, logger):
    logger('Preparing to send email...')
    try:
        msg = MIMEMultipart()
        msg['From'] = email_settings['user']
        msg['To'] = email_settings['to']
        msg['Subject'] = "Automated Workflow Report"

        body = "Please find the attached report generated by the automated workflow."
        msg.attach(MIMEText(body, 'plain'))

        filename = os.path.basename(report_path)
        with open(report_path, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
        
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', f'attachment; filename= {filename}')
        msg.attach(part)

        server = smtplib.SMTP(email_settings['server'], int(email_settings['port']))
        server.starttls()
        server.login(email_settings['user'], email_settings['password'])
        text = msg.as_string()
        server.sendmail(email_settings['user'], email_settings['to'], text)
        server.quit()
        logger('Email sent successfully.')
    except Exception as e:
        logger(f"Failed to send email: {e}", level='error')
        raise e

# --- 4. Streamlit Application UI ---

st.set_page_config(page_title="Workflow Automation Bot", layout="wide")
st.title("📄 Workflow Automation Bot")
st.markdown("This tool automates the process of analyzing data, generating a report, and emailing it.")

# --- UI: Email Settings (Sidebar) ---
st.sidebar.header("📧 Email Settings")
st.sidebar.info("You can set default values using a `.env` file or Streamlit secrets.")
email_settings = {
    'server': st.sidebar.text_input("SMTP Server", value=os.environ.get('SMTP_SERVER', '')),
    'port': st.sidebar.text_input("SMTP Port", value=os.environ.get('SMTP_PORT', '587')),
    'user': st.sidebar.text_input("SMTP User (your email)", value=os.environ.get('SMTP_USER', '')),
    'password': st.sidebar.text_input("SMTP Password", value=os.environ.get('SMTP_PASSWORD', ''), type='password'),
    'to': st.sidebar.text_input("Recipient Email", value=os.environ.get('MAIL_TO', '')),
}

# --- UI: Main Area ---
st.header("1. Upload Excel File")
uploaded_file = st.file_uploader("Choose an Excel file", type=['xlsx', 'xls'])

if uploaded_file is not None:
    try:
        df = pd.read_excel(uploaded_file)
        st.success(f"Successfully loaded `{uploaded_file.name}` with {df.shape[0]} rows and {df.shape[1]} columns.")
        
        st.header("2. Select Chart Column")
        st.markdown("Choose a **numeric** column from your data to visualize.")
        
        # Filter for numeric columns for better user experience
        numeric_columns = df.select_dtypes(include=['number']).columns.tolist()
        if not numeric_columns:
            st.warning("No numeric columns found in the uploaded file to create a chart.")
            selected_column = None
        else:
            selected_column = st.selectbox("Column for Histogram", options=numeric_columns)

        st.header("3. Run Workflow")
        if st.button("🚀 Generate Report and Send Email", type="primary"):
            # --- Workflow Execution ---
            # Check if all settings are provided
            if not all(email_settings.values()):
                st.error("Please configure all email settings in the sidebar first.")
            elif selected_column is None:
                st.error("Cannot run workflow because no numeric column is available for the chart.")
            else:
                log_placeholder = st.container()
                
                # Redefine logger to write into the placeholder
                def workflow_logger(message, level='info'):
                    with log_placeholder:
                        st_logger(message, level)

                try:
                    with st.spinner("Processing... Please wait."):
                        workflow_logger("--- Workflow started. ---")
                        # 1. Validate Data
                        validated_df = validate_data(df, logger=workflow_logger)
                        
                        # 2. Summarize Data
                        data_summary = summarize_data(validated_df, logger=workflow_logger)
                        
                        # 3. Create Visualization
                        chart_path = create_visualization(validated_df, column_to_plot=selected_column, logger=workflow_logger)
                        
                        # 4. Generate PDF Report
                        report_path = generate_pdf_report(data_summary, chart_path, logger=workflow_logger)
                        
                        # 5. Send Email
                        send_email_with_attachment(report_path, email_settings, logger=workflow_logger)

                    st.success(f"--- Workflow successful! Report sent to {email_settings['to']} ---")
                    st.balloons()
                    
                    # Provide download link for the report
                    with open(report_path, "rb") as file:
                        st.download_button(
                            label="📥 Download Generated Report",
                            data=file,
                            file_name=os.path.basename(report_path),
                            mime="application/pdf"
                        )

                except (ValueError, TypeError) as chart_error:
                    workflow_logger(f"Chart Error: Could not create a chart for the column '{selected_column}'. Please ensure it contains only numeric data.", level='error')
                except FileNotFoundError as font_error:
                    workflow_logger(f"Font File Not Found: Please ensure '{os.path.basename(FONT_PATH)}' is in the same directory as the script.", level='error')
                except Exception as e:
                    workflow_logger(f"An unexpected error occurred: {e}", level='error')
                    logging.error(f'An error occurred: {e}', exc_info=True)
                finally:
                    workflow_logger("--- Workflow finished. ---")

    except Exception as e:
        st.error(f"Failed to read or process the Excel file. Error: {e}")

else:
    st.info("Awaiting for an Excel file to be uploaded.")
